@all
Feature:
  Problem 2 - "Even Fibonacci numbers"

  Each new term in the Fibonacci sequence is generated by adding the previous two terms.
  By starting with 1 and 2, the first 10 terms will be:

  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

  Scenario: Get sum of all even-numbered Fibonacci sequence up to 10 digits
    Given that we generate fib sequence up to 10 digits
    Then sum of all even numbered sequence will be 10

  Scenario: Get sum of all even-numbered Fibonacci sequence up to 40 digits
    Given that we generate fib sequence up to 40 digits
    Then sum of all even numbered sequence will be 44

  Scenario: Get sum of all even-numbered Fibonacci sequence up to 4mil digits
    Given that we generate fib sequence up to 4000000 digits
    Then sum of all even numbered sequence will be 4613732

  Scenario: Above using data tables
    When the input value then the output should be as below:
      | input   | output  |
      | 10      | 10      |
      | 40      | 44      |
      | 4000000 | 4613732 |
      | 1000    | 798     |


